[workspace]
members = [
  "aoc",
  "aoc_core",
  "aoc_derive"
]

package.rust-version = "1.90.0"

resolver = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = false

