[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aoc"
path = "src/lib/lib.rs"

[[bin]]
name = "download"
path = "src/bin/download.rs"

[[bin]]
name = "cur"
path = "src/aoc2015/day7.rs"


[[bin]]
name = "temp"
path = "src/temp.rs"

[dependencies]
petgraph = "0.6.3"
md5 = "0.7.0"
# num-traits = "0.2.15"
# aoc-cache = "0.2.1"
