[package]
name = "aoc_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc_core"
path = "src/lib/lib.rs"

[dependencies]
inventory = "0.3.13"
ureq = "2.10.0"
pico-args = "0.5.0"
shellexpand = "3.1.0"
petgraph = "0.6.5"
